# Docker Dependencies and Set-Up
---
- name: Install Docker prerequisites
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release", "software-properties-common"]
    update_cache: yes
  become: yes
  tags:
    - docker
    - dependencies

- name: "APT - Add Docker GPG key for installation"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  tags:
    - docker
    - dependencies

- name: "APT - Register Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker
  become: yes
  tags:
    - docker
    - dependencies

- name: "APT - Install common dependencies"
  apt:
    name: ["docker-ce"]
    update_cache: yes
  become: yes
  tags:
    - docker
    - dependencies