# GitLab Listener Installation & Set-Up
---

# Persist Installation Version

- name: "FILE - Create directory for GitLab Listener version persistence"
  file:
    path: "/var/lib/gitlab-listener/"
    state: directory
  become: yes
  tags:
    - listener

- name: "FILE - Persist GitLab Listener release version"
  copy:
    dest: "/var/lib/gitlab-listener/gitlab-listener-release"
    content: "{{ dep_listener_release_name }}\n"
  become: yes
  register: "dep_listener_release_version"
  tags:
    - listener

# Copy and Install Release

- name: "FILE - Copy GitLab Listener binary release"
  copy:
    src: "{{ dep_listener_release_root }}/{{ dep_listener_release_name }}"
    dest: "/var/tmp/{{ dep_listener_release_name }}"
  when: dep_listener_release_version is changed
  tags:
    - listener
    
- name: "FILE - Remove existing GitLab Listener temporary files"
  file:
    dest: "/var/tmp/gitlab-listener"
    state: absent
  tags:
    - listener

- name: "FILE - Prepare GitLab Listener unarchival directory"
  file:
    dest: "/var/tmp/gitlab-listener"
    state: directory
  when: dep_listener_release_version is changed
  tags:
    - listener

- name: "FILE - Unpack GitLab Listener release"
  unarchive:
    remote_src: yes
    src: "/var/tmp/{{ dep_listener_release_name }}"
    dest: "/var/tmp/gitlab-listener"
  when: dep_listener_release_version is changed
  tags:
    - listener

- name: "FILE - Remove GitLab Listener release archive"
  file:
    dest: "/var/tmp/{{ dep_listener_release_name }}"
    state: absent
  tags:
    - listener

- name: "FILE - Prepare GitLab Listener installation directory"
  file:
    dest: "/usr/local/share/gitlab-listener"
    state: directory
  become: yes
  when: dep_listener_release_version is changed
  tags:
    - listener

- name: "FILE - Install GitLab Listener"
  command: "rsync -av --delete /var/tmp/gitlab-listener/ /usr/local/share/gitlab-listener"
  become: yes
  when: dep_listener_release_version is changed
  tags:
    - listener

- name: "FILE - Link GitLab Listener to binary path"
  file:
    src: "/usr/local/share/gitlab-listener/GitLabListener"
    path: "/usr/local/bin/gitlab-listener"
    state: link
  become: yes
  when: dep_listener_release_version is changed
  tags:
    - listener

- name: "FILE - Create GitLab Listener configuration directory"
  file:
    path: "/usr/local/etc/gitlab-listener"
    state: directory
  become: yes
  tags:
    - listener

- name: "FILE - Link GitLab Listener configuration to system"
  file:
    src: "{{ app_root }}/server/gitlab-listener/listener.plist"
    dest: "/usr/local/etc/gitlab-listener/listener.plist"
    state: link
  become: yes
  tags:
    - listener
    - listener-link

# Set-Up Firewall Rules

- name: "UFW - Allow HTTP connections for listener"
  ufw:
    rule: allow
    proto: tcp
    to_port: "8080"
    comment: "HTTP"
  become: yes
  tags:
	- listener
	- listener-network
  - network

# Copy System Service Definition

- name: "SERVICE - Install GitLab Listener service"
  copy:
    src: "{{ dep_listener_service }}"
    dest: "/etc/systemd/system/gitlab-listener.service"
  become: yes
  tags:
	- listener
	- listener-system-service

# Enable and Start System Service

- name: "SERVICE - Start GitLab Listener service"
  systemd:
    name: gitlab-listener.service
    enabled: yes
    state: started
    daemon_reload: yes
    no_block: yes
  become: yes
  tags:
    - listener
    - listener-system-service