# Swift Set-Up
---
# Install Dependencies

- name: "APT - Install common dependencies"
  apt:
    name:
      [
        "clang",
        "libpython2.7",
        "libpython2.7-dev"
      ]
    update_cache: yes
  become: yes
  tags:
    - swift
    - swift-dependencies
    - dependencies

# Release Version Persistence

- name: "FILE - Create directory for Swift version persistence"
  file:
    path: "/usr/local/var/lib/swift"
    state: directory
  become: yes
  tags:
    - swift
    - dependencies

- name: "FILE - Persist Swift binary release version"
  copy:
    dest: "/usr/local/var/lib/swift/swift-release"
    content: "{{ dep_swift_release }}\n"
  become: yes
  register: "swift_release_version"
  tags:
    - swift
    - dependencies

# Release Download & Set-Up

- name: "FILE - Download Swift release"
  get_url:
    url: "{{ dep_swift_release }}"
    dest: "/tmp/{{ dep_swift_resource }}.tar.gz"
  when: swift_release_version is changed
  tags:
    - swift
    - swift-download
    - dependencies

- name: "FILE - Unpack Swift release download"
  unarchive:
    remote_src: yes
    src: "/tmp/{{ dep_swift_resource }}.tar.gz"
    dest: "/tmp/"
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Install Swift release"
  command: "mv /tmp/{{ dep_swift_resource }} /usr/share/swift"
  become: yes
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Link Swift main executable"
  command: "ln -sf /usr/share/swift/bin/swift /usr/bin/"
  become: yes
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Link Swift dynamic runtime libraries"
  command: "ln -sf /usr/share/swift/usr/lib/swift /usr/lib/"
  become: yes
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Remove temporary Swift archives"
  file:
    dest: "/tmp/{{ dep_swift_resource }}.tar.gz"
    state: absent
  when: swift_release_version is changed
  tags:
    - swift
    - swift-download
    - swift-cleanup
    - dependencies
