# Swift Set-Up
---
# Install Dependencies

- name: "APT - Install common dependencies"
  apt:
    name:
      [
        "clang",
        "libicu-dev",
        "libcurl4",
        "libcurl4-openssl-dev",
        "openssl",
        "libssl-dev",
        "libpython2.7",
        "libpython2.7-dev",
        "uuid-dev",
      ]
    update_cache: yes
  become: yes
  tags:
    - swift
    - swift-dependencies
    - dependencies

# Release Version Persistence

- name: "FILE - Create directory for Swift version persistence"
  file:
    path: "/usr/local/var/lib/swift"
    state: directory
  become: yes
  tags:
    - swift
    - dependencies

- name: "FILE - Persist Swift binary release version"
  copy:
    dest: "/usr/local/var/lib/swift/swift-release"
    content: "{{ dep_swift_release }}\n"
  become: yes
  register: "swift_release_version"
  tags:
    - swift
    - dependencies

# Release Download & Set-Up

- name: "FILE - Download Swift release"
  get_url:
    url: "{{ dep_swift_release }}"
    dest: "/var/tmp/swift-archive.tar.gz"
  when: swift_release_version is changed
  tags:
    - swift
    - swift-download
    - dependencies

- name: "FILE - Unpack Swift release download"
  unarchive:
    remote_src: yes
    src: /var/tmp/swift-archive.tar.gz
    dest: /var/tmp/
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Install Swift release"
  command: "/bin/sh -c 'rsync -av /var/tmp/swift*/usr/ /usr'"
  become: yes
  when: swift_release_version is changed
  tags:
    - swift
    - dependencies

- name: "FILE - Remove temporary Swift archives"
  command: "/bin/sh -c 'rm -rf /var/tmp/swift*'"
  when: swift_release_version is changed
  tags:
    - swift
    - swift-download
    - swift-cleanup
    - dependencies
